DROP TABLE IF EXISTS cstdm_schema.tazdata;

CREATE TABLE cstdm_schema.tazdata (
  ZONE integer,
  DISTRICT integer,
  SD integer,
  COUNTY integer,
  TOTHH integer,
  HHPOP integer,
  TOTPOP integer,
  EMPRES integer,
  SFDU integer,
  MFDU integer,
  HHINCQ1 integer,
  HHINCQ2 integer,
  HHINCQ3 integer,
  HHINCQ4 integer,
  TOTACRE numeric,
  RESACRE integer,
  CIACRE integer,
  SHPOP62P numeric,
  TOTEMP integer,
  AGE0004 integer,
  AGE0519 integer,
  AGE2044 integer,
  AGE4564 integer,
  AGE65P integer,
  RETEMPN integer,
  FPSEMPN integer,
  HEREMPN integer,
  OTHEMPN integer,
  AGREMPN integer,
  MWTEMPN integer,
  PRKCST numeric,
  OPRKCST numeric,
  AREATYPE integer,
  HSENROLL numeric,
  COLLFTE numeric,
  COLLPTE numeric,
  TOPOLOGY numeric,
  TERMINAL numeric,
  ZERO integer,
  hhlds integer,
  sftaz integer,
  gqpop integer
);

\copy cstdm_schema.tazdata FROM 'C:\Users\abharadw\Desktop\CSTDM Post Processing\tazData.csv' DELIMITER ',' CSV HEADER;